### ISSUE TITLE
master-gtk3 - gmoccapy - settings

### ISSUE THREAD

**Issue by gmoccapy** [LinuxCNC/linuxcnc#1182]
settings of Themes and sound does not work

**Comment by andypugh** [comment]
I have been trying to get themes to work with Touchy today, and I think that there may be problems outside our control. 

Touchy now works with _some_ themes, but there are lots of warnings of changed property names.

**Comment by gmoccapy** [comment]
HLo Andy, can you share your touch, stuff, so I can try to adapt that to gmoccapy

Final solution need to be to use css style for customizing the view of the gui

**Comment by andypugh** [comment]
I was hoping that I could have a look to see if the same (naive) fixes would help, but at the moment I can't even start the gmoccapy sample configs in master-gtk3

**Comment by rene-dev** [comment]
why does the ui need to set its theme? whats wrong with using the system theme?
@andypugh which error do you get when starting gmoccapy?

**Comment by andypugh** [comment]
> @andypugh which error do you get when starting gmoccapy?

First a dialog box:
https://photos.app.goo.gl/Xys9JQeVkxkSsmdaA
Then a second dialog box (With Gmoccapy open behind it) 
https://photos.app.goo.gl/GboNxENjSonM5Kh88
Closing the dialog box closes Gmoccapy:

````
andypugh@buster:~/linuxcnc$ linuxcnc
LINUXCNC - 2.9.0~pre0
Machine configuration directory is '/home/andypugh/linuxcnc-dev/configs/sim/gmoccapy'
Machine configuration file is '4_axis.ini'
Starting LinuxCNC...
Found file(REL): ./core_sim4.hal
Note: Using POSIX realtime

trivkins: coordinates:xyzc
   Joint 0 ==> Axis X
   Joint 1 ==> Axis Y
   Joint 2 ==> Axis Z
   Joint 3 ==> Axis C
trivkins: Recommend: kinstype=both

Unexpected realtime delay on task 0 with period 100000
This Message will only display once per session.
Run the Latency Test and resolve before continuing.
Found file(REL): ./spindle_sim.hal
Found file(REL): ./simulated_home.hal
Unexpected realtime delay on task 0 with period 100000
This Message will only display once per session.
Run the Latency Test and resolve before continuing.

Found an error!
The following information may be useful in troubleshooting:

Traceback (most recent call last):
  File "/home/andypugh/linuxcnc-dev/lib/python/gladevcp/iconview.py", line 188, in __init__
    pixbuf = Gtk.IconTheme.get_default().load_icon("gtk-quit", 48, 0)
gi.repository.GLib.GError: gtk-icon-theme-error-quark: Icon 'gtk-quit' not present in theme Tango (0)

task: main loop took 0.538538 seconds
task: main loop took 0.556755 seconds
task: main loop took 0.555996 seconds
task: main loop took 0.578372 seconds
task: main loop took 0.013969 seconds
task: main loop took 0.034967 seconds
task: main loop took 0.030826 seconds
task: main loop took 0.032279 seconds
task: main loop took 0.011937 seconds
task: main loop took 0.021109 seconds
'IconFileSelection' object has no attribute 'store'
'IconFileSelection' object has no attribute 'iconView'
'IconFileSelection' object has no attribute 'store'
'IconFileSelection' object has no attribute 'iconView'
'IconFileSelection' object has no attribute 'on_btn_jump_to'
'IconFileSelection' object has no attribute 'store'
'IconFileSelection' object has no attribute 'iconView'
'IconFileSelection' object has no attribute 'store'
'IconFileSelection' object has no attribute 'iconView'
Icon from stock
0  =  /home/andypugh/linuxcnc-dev/bin/gmoccapy
1  =  -ini
2  =  /home/andypugh/linuxcnc-dev/configs/sim/gmoccapy/4_axis.ini
Entry = trivkins
Entry = coordinates=xyzc
found the following coordinates xyzc

**** GMOCCAPY GETINIINFO **** 
Number of joints = 4
4 COORDINATES found = xyzc
joint 0 = axis x
joint 1 = axis y
joint 2 = axis z
joint 3 = axis c
{0: 'x', 1: 'y', 2: 'z', 3: 'c'}

**** GMOCCAPY GETINIINFO **** 

[KINS] KINESTYPE is trivkins
**** GMOCCAPY GETINIINFO **** 
No MIN_ANGULAR_VELOCITY entry found in [DISPLAY] of INI file
Using default value of 0.1 degree / min
**** GMOCCAPY GETINIINFO **** 
No DEFAULT_ANGULAR_VELOCITY entry found in [DISPLAY] of INI file
Using default value of 360 degree / min
**** GMOCCAPY GETINIINFO **** 
No MAX_ANGULAR_VELOCITY entry found in [DISPLAY] of INI file
Using default value of 3600 degree / min
**** GMOCCAPY GETINIINFO **** 
No MAX_RAPID_OVERRIDE entry found in [DISPLAY] of INI file 
 Default settings 100 % applied!
**** GMOCCAPY GETINIINFO **** 
Preference file path: /home/andypugh/linuxcnc-dev/configs/sim/gmoccapy/gmoccapy_4_axis.pref
**** GMOCCAPY GETINIINFO **** 
 No DEFAULT_SPINDLE_SPEED entry found in [DISPLAY] of INI file
**** GMOCCAPY INFO ****
**** no valid probe config in INI File ****
**** disabled tool measurement ****
**** GMOCCAPY INFO ****
**** Entering make_DRO
axis_list = ['x', 'y', 'z', 'c']
**** GMOCCAPY INFO ****
**** Entering make ref axis button
/home/andypugh/linuxcnc-dev/bin/gmoccapy:717: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  lbl = Gtk.Label("")
Filepath =  /home/andypugh/linuxcnc-dev/share/gmoccapy/images/ref_all.png
get button with image
Filepath =  /home/andypugh/linuxcnc-dev/share/gmoccapy/images/ref_x.png
get button with image
Filepath =  /home/andypugh/linuxcnc-dev/share/gmoccapy/images/ref_y.png
get button with image
Filepath =  /home/andypugh/linuxcnc-dev/share/gmoccapy/images/ref_z.png
get button with image
Filepath =  /home/andypugh/linuxcnc-dev/share/gmoccapy/images/ref_c.png
get button with image
Filepath =  /home/andypugh/linuxcnc-dev/share/gmoccapy/images/unhome.png
get button with image
get button with image
/home/andypugh/linuxcnc-dev/bin/gmoccapy:735: DeprecationWarning: Gtk.Image.set_from_stock is deprecated
  image.set_from_stock(stock, 48)
**** GMOCCAPY INFO ****
**** Entering make touch button
/home/andypugh/linuxcnc-dev/bin/gmoccapy:896: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  btn = Gtk.ToggleButton(_("  edit\noffsets"))
/home/andypugh/linuxcnc-dev/bin/gmoccapy:900: DeprecationWarning: Gtk.Widget.modify_bg is deprecated
  btn.modify_bg(Gtk.StateFlags.ACTIVE, Gdk.color_parse("#FFFF00"))
get button with image
get button with image
get button with image
get button with image
/home/andypugh/linuxcnc-dev/bin/gmoccapy:944: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  btn = Gtk.Button(_("zero\n G92"))
/home/andypugh/linuxcnc-dev/bin/gmoccapy:959: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  btn = Gtk.Button(_("    set\nselected"))
get button with image
**** GMOCCAPY INFO ****
**** Entering make jog increments
**** GMOCCAPY INFO ****
**** Entering make jog button
/home/andypugh/linuxcnc-dev/bin/gmoccapy:1168: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  btn = Gtk.Button(name.upper())
**** GMOCCAPY INFO ****
**** Entering make macro button
found 5 Macros
get button with image
Macro i_am_lost has image link
Image = /home/andypugh/linuxcnc-dev/configs/sim/gmoccapy/macros/images/i_am_lost.png
get button with image
/home/andypugh/linuxcnc-dev/bin/gmoccapy:1239: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label, stock, use_stock" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  btn = Gtk.Button(lbl, None, False)
Macro go_to_position X-pos Y-pos Z-pos has image link
Image = /home/andypugh/linuxcnc-dev/configs/sim/gmoccapy/macros/images/goto_x_y_z.png
get button with image
get button with image
get button with image
**** GMOCCAPY INFO ****
**** arrange DRO
4
**** GMOCCAPY INFO ****
**** Place in table
/home/andypugh/linuxcnc-dev/bin/gmoccapy:1468: DeprecationWarning: Gtk.Table.resize is deprecated
  self.widgets.tbl_DRO.resize(rows, cols)
**** GMOCCAPY INFO ****
**** get DRO order
**** GMOCCAPY INFO ****
**** arrange JOG button
less than 6 axis

(gmoccapy:8138): Gtk-WARNING **: 19:14:59.609: Invalid icon size 48


(gmoccapy:8138): Gtk-WARNING **: 19:14:59.609: Invalid icon size 48

**** GMOCCAPY INFO ****
**** Invalid embedded tab configuration ****
**** No tabs will be added! ****
**** GMOCCAPY INFO ****
**** no audio available! ****
**** PYGST libray not installed? ****
**** is python-gstX.XX installed? ****
**** GMOCCAPY INFO ****
**** Entering init gremlin ****
Kinematics type changed
_set_enable_tooltips =  True
'IconFileSelection' object has no attribute 'store'
'IconFileSelection' object has no attribute 'iconView'
'IconFileSelection' object has no attribute 'store'
'IconFileSelection' object has no attribute 'iconView'
'IconFileSelection' object has no attribute 'on_btn_jump_to'
Found an error!
The following information may be useful in troubleshooting:

Traceback (most recent call last):
  File "/home/andypugh/linuxcnc-dev/bin/gmoccapy", line 5299, in <module>
    app = gmoccapy(sys.argv)
  File "/home/andypugh/linuxcnc-dev/bin/gmoccapy", line 328, in __init__
    self._init_IconFileSelection()
  File "/home/andypugh/linuxcnc-dev/bin/gmoccapy", line 2101, in _init_IconFileSelection
    self.widgets.IconFileSelection1.show_filelabel(False)
  File "/home/andypugh/linuxcnc-dev/lib/python/gladevcp/iconview.py", line 404, in show_filelabel
    self.file_label.hide()
AttributeError: 'IconFileSelection' object has no attribute 'file_label'

Jog Pin Changed
x+
Jog Button released = x+
Jog Pin Changed
x-
Jog Button released = x-
Jog Pin Changed
y+
Jog Button released = y+
Jog Pin Changed
y-
Jog Button released = y-
Jog Pin Changed
z+
Jog Button released = z+
Jog Pin Changed
z-
Jog Button released = z-
Jog Pin Changed
c+
Jog Button released = c+
Jog Pin Changed
c-
Jog Button released = c-
on tool chnage

(gmoccapy:8138): Gtk-WARNING **: 19:15:00.178: Invalid icon size 48


(gmoccapy:8138): Gtk-WARNING **: 19:15:00.178: Invalid icon size 48

_kill_dynamic_childs
Shutting down and cleaning up LinuxCNC...
task: 237979 cycles, min=0.000005, max=0.578372, avg=0.001121, 16 latency excursions (> 10x expected cycle time of 0.001000s)
Note: Using POSIX realtime
LinuxCNC terminated with an error.  You can find more information in the log:
    /home/andypugh/linuxcnc_debug.txt
and
    /home/andypugh/linuxcnc_print.txt
as well as in the output of the shell command 'dmesg' and in the terminal
````

**Comment by gmoccapy** [comment]
No icon gtk quit on theme tango

Can you change the theme and try with clearlooks?
Even this need to be fixed by me🙄

**Comment by andypugh** [comment]
"Clearlooks" isn't the same sort of "theme" as "Tango". 
Tango seems to be an "icon theme" and is also, I think, the default with xfce / the LinuxCNC ISO. 
I selected "Menta" instead and Gmoccapy started right up.

**Comment by gmoccapy** [comment]
I do not know who has fixed that, but it is working as expected
