### ISSUE TITLE
Gmoccapy: gremlin crashes on wrong value for orientation in tool table

### ISSUE THREAD

**Issue by hansu** [LinuxCNC/linuxcnc#1773]
If you enter in a tool table of lathe configuration a value for the orientation that exceeds the range of glcanon's `lathe_shapes` (0-9), and try to change to this tool, you get following error and gremlin is dead until you restart gmoccapy:
```
Traceback (most recent call last):
  File "/home/cnc/linuxcnc/linuxcnc-dev-master/lib/python/gremlin.py", line 275, in expose
    else: self.redraw_ortho()
  File "/home/cnc/linuxcnc/linuxcnc-dev-master/lib/python/rs274/glcanon.py", line 356, in inner
    return f(self, *args, **kw)
  File "/home/cnc/linuxcnc/linuxcnc-dev-master/lib/python/rs274/glcanon.py", line 649, in redraw_ortho
    self.redraw()
  File "/home/cnc/linuxcnc/linuxcnc-dev-master/lib/python/rs274/glcanon.py", line 1368, in redraw
    self.cache_tool(current_tool)
  File "/home/cnc/linuxcnc/linuxcnc-dev-master/lib/python/rs274/glcanon.py", line 1468, in cache_tool
    self.lathetool(current_tool)
  File "/home/cnc/linuxcnc/linuxcnc-dev-master/lib/python/rs274/glcanon.py", line 1799, in lathetool
    dx, dy = self.lathe_shapes[orientation]
IndexError: list index out of range
```

For 2.8 you only get a an empty dialog (see https://forum.linuxcnc.org/gmoccapy/46182-radius-compensation-lathe)

One solution would be to catch this case inside glcanon: https://github.com/LinuxCNC/linuxcnc/blob/master/lib/python/rs274/glcanon.py#L1792-L1800
But how then to pass this to gmoccapy?

Another solution would be to validate the input of the tool table, like it is done in Axis.

**Comment by c-morley** [comment]
I think validating the input in tool offset widget and  catching the error in glcanon (I would just use a general tool shape) would be the way to go.

**Comment by hansu** [comment]
Ok I have now added a validation when changing the value.
But I think it would be also good to validate on load or/and on save.
When an out-of-range was detected on load, I can either set the value to zero or keep it and mark it red.
The latter would need an additional validation on apply (save) but would let the user see the old, wrong value.
Not sure if this effort is really neccesary here.
