### ISSUE TITLE
Gmoccapy not starting "out of the box" on Linux (or WSL)

### ISSUE THREAD

**Issue by smoe** [LinuxCNC/linuxcnc#1933]
Sidenote: I need to thank @hansu to also check WSL. That cannot be used for anything time-critical because of the latencies (330&hairsp;µs for base -> 980 while typing this report, 184&hairsp;µs for servo -> 566) on a 10 yo i7 and Win10, but we should find out where its limits are. The one or other educational value this should well have.

After installation on Debian (regular Linux machine or WSL) the direct execution of /usr/bin/gmoccapy demands first of an environment variable CONFIG_DIR and once that is given, also one for LINUXCNC_TCL_DIR, so I tried
```
LINUXCNC_TCL_DIR=/usr/lib/tcltk/linuxcnc CONFIG_DIR=/usr/share/gmoccapy gmoccapy
```
which led to another error:
```
Traceback (most recent call last):
  File "/usr/bin/gmoccapy", line 5365, in <module>
    app = gmoccapy(sys.argv)
  File "/usr/bin/gmoccapy", line 172, in __init__
    self.stat.poll()
SystemError: <method 'poll' of 'linuxcnc.stat' objects> returned NULL without setting an exception
```
This is a bit cryptic. Preferably, some default paths would have been chosen and the user would just start the binary.

**Comment by smoe** [comment]
Well. I should first have executed linuxcnc. But that is what gmoccapy could have told me, too. The gmoccapy screen starts up (with errors) with the 3 axes mill simulation, but not without a first error box because of
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gladevcp/iconview.py", line 118, in __init__
    pixbuf = Gtk.IconTheme.get_default().load_icon("gtk-home", 48, 0)
gi.repository.GLib.GError: gtk-icon-theme-error-quark: Icon 'gtk-home' not present in theme Adwaita (0)
```
that I could click away, but then the later file icon error kills it. A copy of stdout/err is added below.
```
moeller@DESKTOP-CPG6JS1:~$ linuxcnc
LINUXCNC - 2.9.0~pre0
Machine configuration directory is '/home/moeller/linuxcnc/configs/sim.gmoccapy'
Machine configuration file is 'gmoccapy.ini'

check_config:
  Unexpected multiple values [JOINT_0]HOME: 0.000 10
  Unexpected multiple values [JOINT_1]HOME: 0.000 10
  Unexpected multiple values [JOINT_2]HOME: 0.0 -10

Starting LinuxCNC...
linuxcnc TPMOD=tpmod HOMEMOD=homemod EMCMOT=motmod
Note: Using POSIX non-realtime
Found file(REL): ./core_sim.hal
Found file(REL): ./spindle_sim.hal
Found file(REL): ./simulated_home.hal
link (updating variable file): No such file or directory
/usr/lib/python3/dist-packages/gladevcp/hal_lightbutton.py:20: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Pango, PangoCairo
NVD3D10: CPU cyclestats are disabled on client virtualization
NVD3D10: CPU cyclestats are disabled on client virtualization
Found an error!
The following information may be useful in troubleshooting:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gladevcp/iconview.py", line 118, in __init__
    pixbuf = Gtk.IconTheme.get_default().load_icon("gtk-home", 48, 0)
gi.repository.GLib.GError: gtk-icon-theme-error-quark: Icon 'gtk-home' not present in theme Adwaita (0)

'IconFileSelection' object has no attribute 'store'
'IconFileSelection' object has no attribute 'iconView'
'IconFileSelection' object has no attribute 'store'
'IconFileSelection' object has no attribute 'iconView'
'IconFileSelection' object has no attribute 'on_btn_jump_to'
'IconFileSelection' object has no attribute 'store'
'IconFileSelection' object has no attribute 'iconView'
'IconFileSelection' object has no attribute 'store'
'IconFileSelection' object has no attribute 'iconView'
0  =  /usr/bin/gmoccapy
1  =  -ini
2  =  /home/moeller/linuxcnc/configs/sim.gmoccapy/gmoccapy.ini
Entry = trivkins
Entry = coordinates=xyz
found the following coordinates xyz

**** GMOCCAPY GETINIINFO ****
Number of joints = 3
3 COORDINATES found = xyz
joint 0 = axis x
joint 1 = axis y
joint 2 = axis z
{0: 'x', 1: 'y', 2: 'z'}

**** GMOCCAPY GETINIINFO ****

[KINS] KINESTYPE is trivkins
**** GMOCCAPY GETINIINFO ****
No MIN_ANGULAR_VELOCITY entry found in [DISPLAY] of INI file
Using default value of 0.1 degree / min
**** GMOCCAPY GETINIINFO ****
No DEFAULT_ANGULAR_VELOCITY entry found in [DISPLAY] of INI file
Using default value of 360 degree / min
**** GMOCCAPY GETINIINFO ****
No MAX_RAPID_OVERRIDE entry found in [DISPLAY] of INI file
 Default settings 100 % applied!
**** GMOCCAPY GETINIINFO ****
Preference file path: /home/moeller/linuxcnc/configs/sim.gmoccapy/gmoccapy.pref
No option 'dro_digits' in section: 'DEFAULT'
No option 'dro_size' in section: 'DEFAULT'
No option 'abs_color' in section: 'DEFAULT'
No option 'rel_color' in section: 'DEFAULT'
No option 'dtg_color' in section: 'DEFAULT'
No option 'homed_color' in section: 'DEFAULT'
No option 'unhomed_color' in section: 'DEFAULT'
No option 'enable_dro' in section: 'DEFAULT'
No option 'scale_jog_vel' in section: 'DEFAULT'
No option 'scale_spindle_override' in section: 'DEFAULT'
No option 'scale_feed_override' in section: 'DEFAULT'
No option 'scale_rapid_override' in section: 'DEFAULT'
No option 'spindle_bar_min' in section: 'DEFAULT'
No option 'spindle_bar_max' in section: 'DEFAULT'
No option 'turtle_jog_factor' in section: 'DEFAULT'
No option 'hide_turtle_jog_button' in section: 'DEFAULT'
No option 'unlock_code' in section: 'DEFAULT'
No option 'toggle_readout' in section: 'DEFAULT'
No option 'spindle_start_rpm' in section: 'DEFAULT'
**** GMOCCAPY INFO ****
**** no valid probe config in INI File ****
**** disabled tool measurement ****
**** GMOCCAPY INFO ****
**** Entering make_DRO
axis_list = ['x', 'y', 'z']
**** GMOCCAPY INFO ****
**** Entering make ref axis button
Filepath =  /usr/share/gmoccapy/images/ref_all.png
get button with image
Filepath =  /usr/share/gmoccapy/images/ref_x.png
get button with image
Filepath =  /usr/share/gmoccapy/images/ref_y.png
get button with image
Filepath =  /usr/share/gmoccapy/images/ref_z.png
get button with image
Filepath =  /usr/share/gmoccapy/images/unhome.png
get button with image
get button with image
**** GMOCCAPY INFO ****
**** Entering make touch button
/usr/bin/gmoccapy:922: DeprecationWarning: Gtk.Widget.override_background_color is deprecated
  btn.override_background_color(Gtk.StateFlags.ACTIVE, Gdk.RGBA(1.0, 1.0, 0.0, 1.0))
get button with image
get button with image
get button with image
get button with image
**** GMOCCAPY INFO ****
**** Entering make jog increments
**** GMOCCAPY INFO ****
**** Entering make jog button
**** GMOCCAPY INFO ****
**** Entering make macro button
found 15 Macros
get button with image
Macro go_to_position x-pos y-pos z-pos has image link
Image = /home/moeller/linuxcnc/configs/sim.gmoccapy/macros/images/goto_x_y_z.png
get button with image
Macro i_am_lost has image link
Image = /home/moeller/linuxcnc/configs/sim.gmoccapy/macros/images/i_am_lost.png
get button with image
Macro macro_8 has image link
Image = /home/moeller/linuxcnc/configs/sim.gmoccapy/macros/images/macro_8.png
get button with image
get button with image
get button with image
**** GMOCCAPY INFO ****
**** arrange DRO
3
**** GMOCCAPY INFO ****
**** Place in table
/usr/bin/gmoccapy:1495: DeprecationWarning: Gtk.Table.resize is deprecated
  self.widgets.tbl_DRO.resize(rows, cols)
**** GMOCCAPY INFO ****
**** get DRO order
**** GMOCCAPY INFO ****
**** arrange JOG button
less than 6 axis
No option 'blockheight' in section: 'DEFAULT'
task: main loop took 0.144579 seconds
No option 'open_file' in section: 'DEFAULT'
No option 'screen1' in section: 'DEFAULT'
No option 'x_pos' in section: 'DEFAULT'
No option 'y_pos' in section: 'DEFAULT'
No option 'width' in section: 'DEFAULT'
No option 'height' in section: 'DEFAULT'
**** GMOCCAPY INFO ****
**** Invalid embedded tab configuration ****
**** No tabs will be added! ****
No option 'gtk_theme' in section: 'DEFAULT'
**** GMOCCAPY INFO ****
**** no audio available! ****
**** PYGST library not installed? ****
**** is python-gstX.XX installed? ****
**** GMOCCAPY INFO ****
**** Entering init gremlin ****
No option 'grid_size' in section: 'DEFAULT'
No option 'view' in section: 'DEFAULT'
No option 'mouse_btn_mode' in section: 'DEFAULT'
Kinematics type changed
No option 'hide_cursor' in section: 'DEFAULT'
No option 'hide_tooltips' in section: 'DEFAULT'
_set_enable_tooltips =  True
No option 'system_name_tool' in section: 'DEFAULT'
No option 'system_name_g5x' in section: 'DEFAULT'
No option 'system_name_rot' in section: 'DEFAULT'
No option 'system_name_g92' in section: 'DEFAULT'
No option 'system_name_g54' in section: 'DEFAULT'
No option 'system_name_g55' in section: 'DEFAULT'
No option 'system_name_g56' in section: 'DEFAULT'
No option 'system_name_g57' in section: 'DEFAULT'
No option 'system_name_g58' in section: 'DEFAULT'
No option 'system_name_g59' in section: 'DEFAULT'
No option 'system_name_g59.1' in section: 'DEFAULT'
No option 'system_name_g59.2' in section: 'DEFAULT'
No option 'system_name_g59.3' in section: 'DEFAULT'
'IconFileSelection' object has no attribute 'store'
'IconFileSelection' object has no attribute 'iconView'
'IconFileSelection' object has no attribute 'store'
'IconFileSelection' object has no attribute 'iconView'
No option 'jump_to_dir' in section: 'DEFAULT'
'IconFileSelection' object has no attribute 'on_btn_jump_to'
Found an error!
The following information may be useful in troubleshooting:

Traceback (most recent call last):
  File "/usr/bin/gmoccapy", line 5365, in <module>
    app = gmoccapy(sys.argv)
  File "/usr/bin/gmoccapy", line 345, in __init__
    self._init_IconFileSelection()
  File "/usr/bin/gmoccapy", line 2128, in _init_IconFileSelection
    self.widgets.IconFileSelection1.show_filelabel(False)
  File "/usr/lib/python3/dist-packages/gladevcp/iconview.py", line 404, in show_filelabel
    self.file_label.hide()
AttributeError: 'IconFileSelection' object has no attribute 'file_label'

Jog Pin Changed
x+
Jog Button released = x+
Jog Pin Changed
x-
Jog Button released = x-
Jog Pin Changed
y+
Jog Button released = y+
Jog Pin Changed
y-
Jog Button released = y-
Jog Pin Changed
z+
Jog Button released = z+
Jog Pin Changed
z-
Jog Button released = z-
on tool change
```

**Comment by hansu** [comment]
>gi.repository.GLib.GError: gtk-icon-theme-error-quark: Icon 'gtk-home' not present in theme Adwaita (0)

Oh, I thought was was fixed with https://github.com/LinuxCNC/linuxcnc/pull/1548

**Comment by smoe** [comment]
Ah. Maybe it is. I was using the Debian package that may just not have been updated. I then suggest I'll have another look when https://github.com/LinuxCNC/linuxcnc/pull/1887 is out.

**Comment by hansu** [comment]
A version before April 25th?

**Comment by SebKuzminsky** [comment]
Yes, as you discovered, LinuxCNC GUIs expect to be started by the `linuxcnc` launcher script, not by a human "by hand" from the terminal or similar.

Can you check if this problem still exists in the current tip of master, and close the issue if not?

**Comment by smoe** [comment]
Traveling, will check once I am back. /usr/bin is not the correct location for anything that usr is not meant to execute. Should we move all the GUIs to /usr/lib/linuxcnc/bin?

**Comment by hansu** [comment]
@smoe have you checked that? I guess you are now back from travelling ;-)

**Comment by smoe** [comment]
I do not see that error when now starting GMOCCAPY correcly on Linux, did not yet run WSL again - thank you for the ping.
