### ISSUE TITLE
LCNC 2.9 - hexagui.py doesnt work

### ISSUE THREAD

**Issue by zz912** [LinuxCNC/linuxcnc#2368]
I am trying make own Vismach. I inspired in examples. I found that hexagui.py doesnt work.
Model is loaded, but I cant move or rotate with it.

If I comment:
hexagui.py line: 148
 strut = Track([strut],base_joint_coords, plat_joint_coords, world_coords)

It can be loaded and I can move or rotate with it. But struts are not in correct position 
![hexagui](https://user-images.githubusercontent.com/96618597/222131710-c9f7a82b-f247-48e3-a3a1-cb710f2bf3f9.png)
hexagui.py is the only example that uses "Track". So I don't know if the error is in hexagui.py (bad using Track) or in vismach.py (bad definition Track)

zdenek@CNC:~/linuxcnc/linuxcnc-2.9/src$ halrun
halcmd: loadusr -W hexagui
halcmd: vismach.py: Track: why am i here? world is not in the scene yet
vismach.py: Track: why am i here? world is not in the scene yet
vismach.py: Track: why am i here? world is not in the scene yet
vismach.py: Track: why am i here? world is not in the scene yet
vismach.py: Track: why am i here? world is not in the scene yet
vismach.py: Track: why am i here? world is not in the scene yet
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/zdenek/linuxcnc/linuxcnc-2.9-Tripteron/lib/python/rs274/OpenGLTk.py", line 361, in tkMap
    self.tkExpose()
  File "/home/zdenek/linuxcnc/linuxcnc-2.9-Tripteron/lib/python/rs274/OpenGLTk.py", line 374, in tkExpose
    self.tkRedraw()
  File "/home/zdenek/linuxcnc/linuxcnc-2.9-Tripteron/lib/python/rs274/OpenGLTk.py", line 351, in tkRedraw
    self.redraw()
  File "/home/zdenek/linuxcnc/linuxcnc-2.9-Tripteron/lib/python/vismach.py", line 805, in redraw
    self.model.traverse()
  File "/home/zdenek/linuxcnc/linuxcnc-2.9-Tripteron/lib/python/vismach.py", line 41, in traverse
    p.traverse()
  File "/home/zdenek/linuxcnc/linuxcnc-2.9-Tripteron/lib/python/vismach.py", line 41, in traverse
    p.traverse()
  File "/home/zdenek/linuxcnc/linuxcnc-2.9-Tripteron/lib/python/vismach.py", line 35, in traverse
    p.apply()
  File "/home/zdenek/linuxcnc/linuxcnc-2.9-Tripteron/lib/python/vismach.py", line 169, in apply
    px, py, pz = self.map_coords(px,py,pz,view2world)
  File "/home/zdenek/linuxcnc/linuxcnc-2.9-Tripteron/lib/python/vismach.py", line 152, in map_coords
    wx = tx*transform[0]+ty*transform[4]+tz*transform[8]+transform[12]
TypeError: unsupported operand type(s) for *: 'float' and 'c_double_Array_4'

**Comment by zz912** [comment]
Thank you dngarrett, it works now.
![hexapod](https://user-images.githubusercontent.com/96618597/222656012-0e3fafd5-8027-44d7-8625-6a93d12eb8d1.png)
