### ISSUE TITLE
Run linuxcnc on fedora

### ISSUE THREAD

**Issue by nomi-ramzan** [LinuxCNC/linuxcnc#2604]
## Here are the steps I follow to reproduce the issue:

 1. Install Fedora IOT 37 and following [this link](https://copr.fedorainfracloud.org/coprs/dwrobel/linuxcnc/)

## This is what I expected to happen:
Successfully run linuxcnc on Fedora
## This is what happened instead:
Getting this error

```
[user1@fedora ~]$ linuxcnc -l
LINUXCNC - 2.10.0-0.95.20230511git27c5a90.fc37
Machine configuration directory is '/home/user1/linuxcnc/configs/XYZ-Metric-user1'
Machine configuration file is 'XYZ-Metric-Sample.ini'
Starting LinuxCNC...
linuxcnc TPMOD=tpmod HOMEMOD=homemod EMCMOT=motmod
Found file(REL): ./XYZ-Metric-Sample.hal
Unexpected realtime delay on task 0 with period 100000
This Message will only display once per session.
Run the Latency Test and resolve before continuing.
Found file(REL): ./custom.hal
Unexpected realtime delay on task 0 with period 100000
This Message will only display once per session.
Run the Latency Test and resolve before continuing.

[Gmoccapy][ERROR]  Found an error!
The following information may be useful in troubleshooting:

Traceback (most recent call last):
  File "/usr/bin/gmoccapy", line 5750, in <module>
    import gladevcp.makepins
  File "/usr/lib/python3.11/site-packages/gladevcp/__init__.py", line 1, in <module>
    from .hal_pythonplugin import *
  File "/usr/lib/python3.11/site-packages/gladevcp/hal_pythonplugin.py", line 30, in <module>
    from .hal_gremlin import HAL_Gremlin
  File "/usr/lib/python3.11/site-packages/gladevcp/hal_gremlin.py", line 36, in <module>
    import gremlin
  File "/usr/lib/python3.11/site-packages/gremlin.py", line 100, in <module>
    class Gremlin(Gtk.DrawingArea,rs274.glcanon.GlCanonDraw,glnav.GlNavBase):
  File "/usr/lib/python3.11/site-packages/gremlin.py", line 101, in Gremlin
    xlib = cdll.LoadLibrary('libX11.so')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libX11.so: cannot open shared object file: No such file or directory
 (gmoccapy:62)
Shutting down and cleaning up LinuxCNC...
task: 1304 cycles, min=0.000032, max=0.011451, avg=0.009991, 0 latency excursions (> 10x expected cycle time of 0.010000s)
LinuxCNC terminated with an error.  You can find more information in the log:
    /home/user1/linuxcnc_debug.txt
and
    /home/user1/linuxcnc_print.txt
as well as in the output of the shell command 'dmesg' and in the terminal

```

## Information about my hardware and software:

 * log file `/home/user1/linuxcnc_print.txt`:
   ```
    RUN_IN_PLACE=no
    LINUXCNC_DIR=
    LINUXCNC_BIN_DIR=/usr/bin
    LINUXCNC_TCL_DIR=/usr/lib64/tcl8.6/linuxcnc2.10.0
    LINUXCNC_SCRIPT_DIR=
    LINUXCNC_RTLIB_DIR=/usr/lib/linuxcnc/modules
    LINUXCNC_CONFIG_DIR=
    LINUXCNC_LANG_DIR=/usr/lib/tcltk/linuxcnc/msgs
    INIVAR=inivar
    HALCMD=halcmd
    LINUXCNC_EMCSH=/usr/bin/wish8.6
    Using previous INI file: /home/user1/linuxcnc/configs/XYZ-Metric-user1/XYZ-Metric-Sample.ini
    INIFILE=/home/user1/linuxcnc/configs/XYZ-Metric-user1/XYZ-Metric-Sample.ini
    VERSION=1.1
    PARAMETER_FILE=linuxcnc.var
    TPMOD=
    HOMEMOD=
    TASK=milltask
    HALUI=halui
    DISPLAY=gmoccapy
    COORDINATES=X Y Z
    KINEMATICS=trivkins coordinates=XYZ
    Starting LinuxCNC server program: linuxcncsvr
    Loading Real Time OS, RTAPI, and HAL_LIB modules
    Starting LinuxCNC IO program: io
    Starting HAL User Interface program: halui
    Starting TASK program: milltask
    Starting DISPLAY program: gmoccapy
    Removing HAL_LIB, RTAPI, and Real Time OS modules
    Removing NML shared memory segments
   ```
 * I am using this Linux distribution and version (often, shown by `cat /etc/os-release`): 
   ```
    NAME="Fedora Linux"
    VERSION="37 (KDE Plasma)"
    ID=fedora
    VERSION_ID=37
    VERSION_CODENAME=""
    PLATFORM_ID="platform:f37"
    PRETTY_NAME="Fedora Linux 37 (KDE Plasma)"
    ANSI_COLOR="0;38;2;60;110;180"
    LOGO=fedora-logo-icon
    CPE_NAME="cpe:/o:fedoraproject:fedora:37"
    DEFAULT_HOSTNAME="fedora"
    HOME_URL="https://fedoraproject.org/"
    DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f37/system-administrators-guide/"
    SUPPORT_URL="https://ask.fedoraproject.org/"
    BUG_REPORT_URL="https://bugzilla.redhat.com/"
    REDHAT_BUGZILLA_PRODUCT="Fedora"
    REDHAT_BUGZILLA_PRODUCT_VERSION=37
    REDHAT_SUPPORT_PRODUCT="Fedora"
    REDHAT_SUPPORT_PRODUCT_VERSION=37
    VARIANT="KDE Plasma"
    VARIANT_ID=kde
```
 * I am using this kernel version (shown by `uname -a`): Linux fedora 6.0.7-301.fc37.aarch64 #1 SMP PREEMPT_DYNAMIC Fri Nov 4 18:13:35 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

 * I am running ...
   - [ ] A binary version from linuxcnc.org (including buildbot.linuxcnc.org)
   - [ ] A binary I built myself
   - [x] A binary version from some other source besides linuxcnc.org: (source https://copr.fedorainfracloud.org/coprs/dwrobel/linuxcnc/)
 * I am using this LinuxCNC version (shown in package manager or, for git versions, `scripts/get-version-from-git`): v2.10.0-pre0-1542-g93fccc095b
 * I am using this user interface (GUI) (e.g., AXIS, Touchy, gmoccapy, etc): gmoccapy
 * I am using this interface hardware vendor and chipset (e.g., parallel port, ethernet port, FPGA card): GPIO on raspberry pi 4b 8GB

**Comment by nomi-ramzan** [comment]
Installed `libX11-devel` and problem solved.
