### ISSUE TITLE
module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by garyemiller** [LinuxCNC/linuxcnc#2825]
Just built on Gentoo from git head:

````
$ bin/image-to-gcode /tmp/Screenshot_2024-01-02_12-38-54.png 
/home/gem/src/linuxcnc/bin/image-to-gcode:772: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  nim = numpy.fromstring(tobytes(im), dtype=numpy.uint8).reshape((h, w)).astype(numpy.float32)
Traceback (most recent call last):
  File "/home/gem/src/linuxcnc/bin/image-to-gcode", line 837, in <module>
    main()
  File "/home/gem/src/linuxcnc/bin/image-to-gcode", line 773, in main
    options = ui(im, nim, im_name)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/gem/src/linuxcnc/bin/image-to-gcode", line 522, in ui
    ui_image = im.resize((nw,nh), Image.ANTIALIAS)
                                  ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
````

**Comment by havardAasen** [comment]
If you are using master, the fix was included a couple of hours ago.

**Comment by garyemiller** [comment]
Works now.  Thanks!

I do get this:

```` $ bin/image-to-gcode /tmp/Screenshot_2024-01-02_12-38-54.png 
/home/gem/src/linuxcnc/bin/image-to-gcode:772: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  nim = numpy.fromstring(tobytes(im), dtype=numpy.uint8).reshape((h, w)).astype(numpy.float32)
````

Should I file a new issue on that?

**Comment by havardAasen** [comment]
> ```
> /home/gem/src/linuxcnc/bin/image-to-gcode:772: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
>   nim = numpy.fromstring(tobytes(im), dtype=numpy.uint8).reshape((h, w)).astype(numpy.float32)
> ```
> 
> Should I file a new issue on that?

No need, I created #2843 to fix that.

**Comment by garyemiller** [comment]
Thanks!
