### ISSUE TITLE
2.10 configuration industrial.ini is broken

### ISSUE THREAD

**Issue by zz912** [LinuxCNC/linuxcnc#3145]
I use RIP instalation Master Branche

I cannot open configuration:
linuxcnc-master/configs/sim/gscreen/gscreen_custom/industrial.ini

In 2.9 branche it works.

Log:
```
zdenek@cnc:~/linuxcnc/linuxcnc-master/scripts$ ./linuxcnc
LINUXCNC - 2.10.0~pre0
Machine configuration directory is '/home/zdenek/linuxcnc/linuxcnc-master/configs/sim/gscreen/gscreen_custom'
Machine configuration file is 'industrial.ini'
Starting LinuxCNC...
linuxcncsvr (144874) emcsvr: machine 'Linuxcnc-Gscreen_gaxis'  version '1.1'
linuxcnc TPMOD=tpmod HOMEMOD=homemod EMCMOT=motmod
Note: Using POSIX realtime
milltask (144888) task: machine 'Linuxcnc-Gscreen_gaxis'  version '1.1'
halui (144890) halui: machine 'Linuxcnc-Gscreen_gaxis'  version '1.1'
Found file(lib): /home/zdenek/linuxcnc/linuxcnc-master/lib/hallib/core_sim.hal
Found file(lib): /home/zdenek/linuxcnc/linuxcnc-master/lib/hallib/sim_spindle_encoder.hal
Found file(lib): /home/zdenek/linuxcnc/linuxcnc-master/lib/hallib/axis_manualtoolchange.hal
Found file(lib): /home/zdenek/linuxcnc/linuxcnc-master/lib/hallib/simulated_home.hal
USRMOT: ERROR: command 30 timeout
emcMotionInit: emcTrajInit failed
link (updating variable file): Adresář nebo soubor neexistuje
[GScreen][DEBUG]  DEBUGGING logging on (gscreen:73)
[GScreen.QTVCP.QT_ISTAT][DEBUG]  INI Path: /home/zdenek/linuxcnc/linuxcnc-master/configs/sim/gscreen/gscreen_custom/industrial.ini (qt_istat.py:64)
[GScreen.QTVCP.QT_ISTAT][DEBUG]  Machine is IMPERIAL based. unit Conversion constant=25.4 (qt_istat.py:163)
[GScreen.QTVCP.QT_ISTAT][DEBUG]  TRAJ COORDINATES: XYZ (qt_istat.py:178)
[GScreen.QTVCP.QT_ISTAT][WARNING]  INI Parsing Error, No MIN_LINEAR_VELOCITY Entry in DISPLAY, Using: 0 (qt_istat.py:651)
[GScreen.QTVCP.QT_ISTAT][DEBUG]  DEFAULT_LINEAR_VELOCITY = 15.0 (qt_istat.py:361)
[GScreen.QTVCP.QT_ISTAT][DEBUG]  MIN_LINEAR_VELOCITY = 0.0 (qt_istat.py:362)
[GScreen.QTVCP.QT_ISTAT][DEBUG]  MAX_LINEAR_VELOCITY = 72.0 (qt_istat.py:363)
[GScreen.QTVCP.QT_ISTAT][DEBUG]  DEFAULT_ANGULAR_VELOCITY = 360.0 (qt_istat.py:368)
[GScreen.QTVCP.QT_ISTAT][DEBUG]  MIN_ANGULAR_VELOCITY = 0.0 (qt_istat.py:369)
[GScreen.QTVCP.QT_ISTAT][DEBUG]  MAX_ANGULAR_VELOCITY = 3600.0 (qt_istat.py:370)
[GScreen.QTVCP.QT_ISTAT][WARNING]  INI Parsing Error, No DEFAULT_SPINDLE_0_SPEED Entry in DISPLAY, Using: 200 (qt_istat.py:651)
[GScreen.QTVCP.QT_ISTAT][WARNING]  INI Parsing Error, No MIN_SPINDLE_0_SPEED Entry in DISPLAY, Using: 100 (qt_istat.py:651)
[GScreen.QTVCP.QT_ISTAT][WARNING]  INI Parsing Error, No MAX_SPINDLE_0_SPEED Entry in DISPLAY, Using: 2500 (qt_istat.py:651)
[GScreen.QTVCP.QT_ISTAT][WARNING]  INI Parsing Error, No MAX_SPINDLE_0_OVERRIDE Entry in DISPLAY, Using: 1 (qt_istat.py:651)
[GScreen.QTVCP.QT_ISTAT][WARNING]  INI Parsing Error, No MIN_SPINDLE_0_OVERRIDE Entry in DISPLAY, Using: 0.5 (qt_istat.py:651)
[GScreen][INFO]  Desktop notifications are available (gscreen:122)
[GScreen][INFO]  Audio alerts are available! (gscreen:133)
[GScreen][INFO]  Skin name = industrial (gscreen:515)
[GScreen][INFO]   Using skin glade file from /home/zdenek/linuxcnc/linuxcnc-master/share/gscreen/skins/industrial/industrial.glade (gscreen:559)
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
Got unknown property in <<set_style>>
[GScreen][INFO]  No Screen 2 glade file present (gscreen:589)
[GScreen][DEBUG]  Handler file path: ['/home/zdenek/linuxcnc/linuxcnc-master/share/gscreen/skins/industrial/industrial_handler.py'] (gscreen:661)
[GScreen][INFO]  Adding import dir /home/zdenek/linuxcnc/linuxcnc-master/share/gscreen/skins/industrial (gscreen:444)
[GScreen][INFO]  Module 'industrial_handler' imported OK (gscreen:450)
[GScreen][INFO]  Module 'industrial_handler': 'get_handlers' function found (gscreen:461)
[GScreen][DEBUG]  Registering handlers in module 'industrial_handler' object '<industrial_handler.HandlerClass object at 0x7fefdb1e4ad0>' (gscreen:470)
[GScreen][DEBUG]  Register callback 'connect_signals' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'init_dro' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'init_sensitive_edit_mode' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'initialize_widgets' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'on_abs_colorbutton_color_set' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'on_button_edit_clicked' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'on_diameter_mode_pressed' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'on_dtg_colorbutton_color_set' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'on_estop_clicked' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'on_hal_status_axis_homed' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'on_hal_status_not_all_homed' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'on_machine_state_clicked' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'on_mdi_button_clicked' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'on_metric_select_clicked' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'on_offsetpage_button_clicked' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'on_rel_colorbutton_color_set' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'on_run_button_clicked' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'on_setup_button_clicked' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'on_show_dtg_pressed' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'on_system_button_clicked' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'on_tooledit_button_clicked' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'periodic' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'system_dialog' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'toggle_modes' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Register callback 'update_mdi_spindle_button' in industrial_handler (gscreen:479)
[GScreen][DEBUG]  Preference file path: None (gscreen:668)
[GScreen][INFO]  Overriding internal signal call to 'on_estop_clicked' (gscreen:3343)
[GScreen][DEBUG]  Traceback (most recent call last):
                  File "/home/zdenek/linuxcnc/linuxcnc-master/bin/gscreen", line 3354, in connect_signals
                  self.widgets[i[1]].connect(i[2], self[i[3]])
                  ~~~~~~~~~~~~^^^^^^
                  File "/home/zdenek/linuxcnc/linuxcnc-master/bin/gscreen", line 290, in __getitem__
                  if r is None: raise IndexError(_("No widget '{}'").format(attr))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  IndexError: No widget 'button_menu' (gscreen:3363)
[GScreen][ERROR]  Could not connect 'button_menu' to 'on_mode_select_clicked' (gscreen:3364)
[GScreen][DEBUG]  Traceback (most recent call last):
                  File "/home/zdenek/linuxcnc/linuxcnc-master/bin/gscreen", line 3354, in connect_signals
                  self.widgets[i[1]].connect(i[2], self[i[3]])
                  ~~~~~~~~~~~~^^^^^^
                  File "/home/zdenek/linuxcnc/linuxcnc-master/bin/gscreen", line 290, in __getitem__
                  if r is None: raise IndexError(_("No widget '{}'").format(attr))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  IndexError: No widget 'button_toggle_readout2' (gscreen:3363)
[GScreen][ERROR]  Could not connect 'button_toggle_readout2' to 'on_button_toggle_readout_clicked' (gscreen:3364)
[GScreen][DEBUG]  Traceback (most recent call last):
                  File "/home/zdenek/linuxcnc/linuxcnc-master/bin/gscreen", line 3354, in connect_signals
                  self.widgets[i[1]].connect(i[2], self[i[3]])
                  ~~~~~~~~~~~~^^^^^^
                  File "/home/zdenek/linuxcnc/linuxcnc-master/bin/gscreen", line 290, in __getitem__
                  if r is None: raise IndexError(_("No widget '{}'").format(attr))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  IndexError: No widget 'button_show_offsets' (gscreen:3363)
[GScreen][ERROR]  Could not connect 'button_show_offsets' to 'on_button_show_offsets_clicked' (gscreen:3364)
[GScreen][DEBUG]  Traceback (most recent call last):
                  File "/home/zdenek/linuxcnc/linuxcnc-master/bin/gscreen", line 3354, in connect_signals
                  self.widgets[i[1]].connect(i[2], self[i[3]])
                  ~~~~~~~~~~~~^^^^^^
                  File "/home/zdenek/linuxcnc/linuxcnc-master/bin/gscreen", line 290, in __getitem__
                  if r is None: raise IndexError(_("No widget '{}'").format(attr))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  IndexError: No widget 'button_select_rotary_adjust' (gscreen:3363)
[GScreen][ERROR]  Could not connect 'button_select_rotary_adjust' to 'on_button_select_rotary_adjust_clicked' (gscreen:3364)
[GScreen][INFO]  Overriding internal signal call to 'on_diameter_mode_pressed' (gscreen:3343)
[GScreen][INFO]  Overriding internal signal call to 'on_button_edit_clicked' (gscreen:3343)
[GScreen][INFO]  Overriding internal signal call to 'on_show_dtg_pressed' (gscreen:3343)
[GScreen][INFO]  Overriding internal signal call to 'on_hal_status_axis_homed' (gscreen:3343)
[GScreen][INFO]  Overriding internal signal call to 'on_hal_status_not_all_homed' (gscreen:3343)
[GScreen][INFO]  Overriding internal signal call to 'on_dtg_colorbutton_color_set' (gscreen:3343)
[GScreen][INFO]  Overriding internal signal call to 'on_abs_colorbutton_color_set' (gscreen:3343)
[GScreen][INFO]  Overriding internal signal call to 'on_rel_colorbutton_color_set' (gscreen:3343)
[GScreen][INFO]  Overriding internal signal call to 'on_metric_select_clicked' (gscreen:3343)
[GScreen][CRITICAL]  Traceback (most recent call last):
                     File "/home/zdenek/linuxcnc/linuxcnc-master/bin/gscreen", line 4781, in <module>
                     app = Gscreen()
                     ^^^^^^^^^
                     File "/home/zdenek/linuxcnc/linuxcnc-master/bin/gscreen", line 842, in __init__
                     self.handler_instance.initialize_widgets()
                     File "/home/zdenek/linuxcnc/linuxcnc-master/share/gscreen/skins/industrial/industrial_handler.py", line 317, in initialize_widgets
                     self.init_dro() # local function
                     ^^^^^^^^^^^^^^^
                     File "/home/zdenek/linuxcnc/linuxcnc-master/share/gscreen/skins/industrial/industrial_handler.py", line 373, in init_dro
                     self.on_abs_colorbutton_color_set(None)
                     File "/home/zdenek/linuxcnc/linuxcnc-master/share/gscreen/skins/industrial/industrial_handler.py", line 249, in on_abs_colorbutton_color_set
                     self.widgets[axis].set_style("labelcolor", color )
                     File "/home/zdenek/linuxcnc/linuxcnc-master/lib/python/gladevcp/drowidget.py", line 342, in set_style
                     replacement_string = ".labelcolor  {color: " + Data + ";}"
                     ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
                     TypeError: can only concatenate str (not "NoneType") to str (gscreen:4787)
[GScreen][ERROR]  Exception #1
                  Traceback (most recent call last):
                  File "/home/zdenek/linuxcnc/linuxcnc-master/bin/gscreen", line 4788, in <module>
                  postgui_halfile,inifile = Gscreen.postgui(app)
                  ^^^
                  NameError: name 'app' is not defined (gscreen:224)
Shutting down and cleaning up LinuxCNC...
task: 0 cycles, min=0.000005, max=0.002016, avg=-1.000000, 0 latency excursions (> 10x expected cycle time of 0.001000s)
Note: Using POSIX realtime
LinuxCNC terminated with an error.  You can find more information in the log:
    /home/zdenek/linuxcnc_debug.txt
and
    /home/zdenek/linuxcnc_print.txt
as well as in the output of the shell command 'dmesg' and in the terminal
```

**Comment by andypugh** [comment]
I am a bit confused by this, I had it working recently.

**Comment by zz912** [comment]
I'm sorry if it's my fault. I tested it on 2 PCs.

**Comment by zz912** [comment]
It works now.
