### ISSUE TITLE
sim/axis/halui_pyvcp fails to start with python3

### ISSUE THREAD

**Issue by rene-dev** [LinuxCNC/linuxcnc#821]
> Traceback (most recent call last):
  File "/home/rene/dev/linuxcnc-stock/lib/python/bwidget.py", line 50, in w
    return self.nametowidget(r)
  File "/home/rene/dev/linuxcnc-stock/lib/python/bwidget.py", line 80, in nametowidget
    w = w.children[name]
KeyError: 'fAxis X'

**Comment by rene-dev** [comment]
Im not sure what fixed this, but its working now.
