### ISSUE TITLE
sim/axis/ngcgui fails to start with python3

### ISSUE THREAD

**Issue by rene-dev** [LinuxCNC/linuxcnc#822]
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/rene/dev/linuxcnc-stock/bin/axis", line 2919, in inifindall
    return root_window.tk.merge(*items)
AttributeError: '_tkinter.tkapp' object has no attribute 'merge'

**Comment by rene-dev** [comment]
looks like its fixed. thanks!
