### ISSUE TITLE
linuxcnc does not start when first launched with python3

### ISSUE THREAD

**Issue by rene-dev** [LinuxCNC/linuxcnc#835]
for some reason you need to launch a version with python2 first.

LINUXCNC - 2.9.0~pre0
Machine configuration directory is '/home/end/linuxcnc/configs/sim/axis'
Machine configuration file is 'axis.ini'
Starting LinuxCNC...
Found file(lib): /home/end/linuxcnc/lib/hallib/core_sim.hal
Note: Using POSIX non-realtime
Found file(lib): /home/end/linuxcnc/lib/hallib/sim_spindle_encoder.hal
Found file(lib): /home/end/linuxcnc/lib/hallib/axis_manualtoolchange.hal
Found file(lib): /home/end/linuxcnc/lib/hallib/simulated_home.hal
Found file(lib): /home/end/linuxcnc/lib/hallib/check_xyz_constraints.hal
link (updating variable file): No such file or directory
No option 'tto_g11' in section: 'DEFAULT'
Traceback (most recent call last):
  File "/usr/lib/python3.7/configparser.py", line 788, in get
    value = d[option]
  File "/usr/lib/python3.7/collections/__init__.py", line 914, in getitem
    return self.missing(key)            # support subclasses that define missing
  File "/usr/lib/python3.7/collections/__init__.py", line 906, in missing
    raise KeyError(key)
KeyError: 'tto_g11'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/end/linuxcnc/bin/axis", line 110, in getpref
    o = m(self, "DEFAULT", option)
  File "/usr/lib/python3.7/configparser.py", line 828, in getboolean
    raw=raw, vars=vars, fallback=fallback, **kwargs)
  File "/usr/lib/python3.7/configparser.py", line 808, in _get_conv
    **kwargs)
  File "/usr/lib/python3.7/configparser.py", line 802, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.7/configparser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'tto_g11' in section: 'DEFAULT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/end/linuxcnc/bin/axis", line 2993, in <module>
    vars.tto_g11.set(ap.getpref("tto_g11", False))
  File "/home/end/linuxcnc/bin/axis", line 113, in getpref
    self.set("DEFAULT", option, default)
  File "/usr/lib/python3.7/configparser.py", line 1197, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/lib/python3.7/configparser.py", line 1182, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
Shutting down and cleaning up LinuxCNC...
task: 164 cycles, min=0.000026, max=0.003707, avg=0.001288, 0 latency excursions (> 10x expected cycle time of 0.001000s)
Note: Using POSIX non-realtime
LinuxCNC terminated with an error.  You can find more information in the log:

**Comment by rene-dev** [comment]
@dngarrett does this fix the issue?

**Comment by rene-dev** [comment]
working, thanks @dngarrett
